import ProgressBar from "@/providers/progress-bar";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/homepage-components/navbar";
import DialogQuoate from "./_components/dialog-quote";
import AOS from "aos"
import "aos/dist/aos.css";
import Footer from "./_components/footer";
const poppins = Poppins({
  subsets: ['latin'], weight: ['400']
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
         <ProgressBar>
        <Navbar/>
        {children}
        <Footer/>
         </ProgressBar>
        </body>
        <DialogQuoate triggerTxtBg positionFixed triggerTxt= 'Request a Quote' title= 'Request a Quote'/>
    </html>
  );
}
